[[constraint]]
  name = "github.com/fatih/color"
  version = "~1.5.0"

[[constraint]]
  name = "github.com/skratchdot/open-golang"
  revision = "75fb7ed4208cf72d323d7d02fd1a5964a7a9073c"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "^1.20"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "~1.12.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.0"